### PR TITLE
[Bug] Fix quotes

### PR DESCRIPTION
**Pull request by Firesphere**
Fix issue #167 by removing double escaping.

A better solution should be implemented at some time, but for now this seems to work.

### CODE REVIEW

**Comment by phptek** [comment]
While the suggested patch now returns _some_ results, and is indubitably fixes _a_ bug, the outcome doesn't match any of the four desirable outcomes listed in #167. 

Note also, there are still repeated double quotes with the patch implemented:

Search Term ("Working Together") --> "https://mysite/search/SearchForm?Search=%22Working+together%22&searchlocale=en_NZ"

```
public function escapeSearch($searchTerm, Helper $helper): string
{
...
...
        var_dump($term);
        die;

        return implode(' ', $term);
}
```

Result:

```
/vagrant/vendor/firesphere/solr-search/src/Factories/QueryComponentFactory.php:280:
array (size=1)
  0 => string '""Working together""' (length=20)
```

**Comment by Firesphere** [comment]
It is expected that the term is enclosed in double quotes twice. Because that's the term being sent to Solr. The actual term sent is single quoted.

Does it still affect your results?

**Comment by phptek** [comment]
This is an improvement for sure, but doesn't address the core issue in its entirety viz one of the 4 expected outcomes as stated in #167.

**Comment by phptek** [comment]
> It is expected that the term is enclosed in double quotes twice. Because that's the term being sent to Solr. The actual term sent is single quoted.
> 
> Does it still affect your results?

Yes.

Before: No results when using quotes.
After: Several results when using quotes - _but_ the page I searched for, using its exact title, that I can find by the same title in my database and via Solr's UI, does not appear :-(

**Comment by Firesphere** [comment]
Which outcome do you expect from this change, and which outcome actually happens?

I've tested this locally against a dataset of 300k items, and it properly takes quoted searches in to account right now.

Your dump does not match up with the actual query executed, so it's hard to tell. Are you on this branch?

**Comment by phptek** [comment]
FCUK. Subsites exclusions were incorrectly filtering out the desired results.

**Pull request merged**
